### ISSUE TITLE
File example does not compile with cursive 0.11

### ISSUE THREAD

**Issue by linclelinkpart5** [BonsaiDen/cursive_tree_view#13]
I get the following errors:

```
   Compiling cursive-test v0.1.0 (/home/lemoine/Projects/rust/cursive-test)
error[E0282]: type annotations needed
  --> src/file_tree.rs:94:51
   |
94 |     tree.set_on_collapse(|siv: &mut Cursive, row, is_collapsed, children| {
   |                                                   ^^^^^^^^^^^^ consider giving this closure parameter a type
   |
   = note: type must be known at this point

error[E0277]: the trait bound `cursive_tree_view::TreeView<file_tree::main::TreeEntry>: cursive::view::view_wrapper::ViewWrapper` is not satisfied
  --> src/file_tree.rs:96:17
   |
96 |             siv.call_on_id("tree", move |tree: &mut TreeView<TreeEntry>| {
   |                 ^^^^^^^^^^ the trait `cursive::view::view_wrapper::ViewWrapper` is not implemented for `cursive_tree_view::TreeView<file_tree::main::TreeEntry>`
   |
   = note: required because of the requirements on the impl of `cursive::view::view_trait::View` for `cursive_tree_view::TreeView<file_tree::main::TreeEntry>`

error[E0599]: no method named `with_id` found for type `cursive_tree_view::TreeView<file_tree::main::TreeEntry>` in the current scope
   --> src/file_tree.rs:106:39
    |
106 |     siv.add_layer(Dialog::around(tree.with_id("tree")).title("File View"));
    |                                       ^^^^^^^
    |
    = note: the method `with_id` exists but the following trait bounds were not satisfied:
            `&cursive_tree_view::TreeView<file_tree::main::TreeEntry> : cursive::view::identifiable::Identifiable`
            `&mut cursive_tree_view::TreeView<file_tree::main::TreeEntry> : cursive::view::identifiable::Identifiable`
            `cursive_tree_view::TreeView<file_tree::main::TreeEntry> : cursive::view::identifiable::Identifiable`
    = help: items from traits can only be used if the trait is in scope
    = note: the following trait is implemented but not in scope, perhaps add a `use` for it:
            `use cursive::view::identifiable::Identifiable;
```

**Comment by gyscos** [comment]
Version 0.4 should now work with cursive 0.12 (the current version).
