### ISSUE TITLE
Examples do not compile with cursive 0.8 and 0.9

### ISSUE THREAD

**Issue by gsurrel** [BonsaiDen/cursive_tree_view#6]
I created a new project with Cursive 0.9 (or 0.8)  and I couldn't compile when adding cursive_tree_view:
```
[dependencies]
cursive = "0.9"
```

From the basic example, here is the error:
```
cargo run --example basic
   Compiling cursive_tree_view v0.2.1 (file:///path/cursive_tree_view)
error[E0310]: the parameter type `T` may not live long enough
   --> src/lib.rs:427:26
    |
427 | impl<T: Display + Debug> View for TreeView<T> {
    |      --                  ^^^^
    |      |
    |      help: consider adding an explicit lifetime bound `T: 'static`...
    |
note: ...so that the type `TreeView<T>` will meet its required lifetime bounds
   --> src/lib.rs:427:26
    |
427 | impl<T: Display + Debug> View for TreeView<T> {
    |                          ^^^^

error[E0310]: the parameter type `T` may not live long enough
   --> src/lib.rs:427:26
    |
427 | impl<T: Display + Debug> View for TreeView<T> {
    |      --                  ^^^^
    |      |
    |      help: consider adding an explicit lifetime bound `T: 'static`...
    |
note: ...so that the type `T` will meet its required lifetime bounds
   --> src/lib.rs:427:26
    |
427 | impl<T: Display + Debug> View for TreeView<T> {
    |                          ^^^^

error: aborting due to 2 previous errors
```

**Comment by gyscos** [comment]
Thanks for the report! This should hopefully be fixed in the latest master.
